"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { Navbar } from "@/components/layout/Navbar";
import { COUNTRIES, Country } from "@/lib/countries-data";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight, Search, BrainCircuit, Globe2, RefreshCw } from "lucide-react";
import { CountryDetailsDialog } from "@/components/flags/CountryDetailsDialog";

export default function Home() {
  const [randomCountry, setRandomCountry] = useState<Country | null>(null);
  const [selectedCountry, setSelectedCountry] = useState<Country | null>(null);

  useEffect(() => {
    pickRandomCountry();
  }, []);

  function pickRandomCountry() {
    const idx = Math.floor(Math.random() * COUNTRIES.length);
    setRandomCountry(COUNTRIES[idx]);
  }

  return (
    <div className="min-h-screen bg-background pb-20">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-16 pb-24 md:pt-32 md:pb-40">
        <div className="container mx-auto px-4 relative z-10 text-center space-y-8 max-w-4xl">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 text-primary font-medium text-sm border border-primary/20 mb-4 animate-in fade-in slide-in-from-bottom-2 duration-700">
            <Globe2 className="h-4 w-4" />
            <span>Discover the World Through Flags</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-headline font-black tracking-tight text-foreground leading-[1.1] animate-in fade-in slide-in-from-bottom-4 duration-700 delay-100">
            Learn, Explore, and <span className="text-primary">Master Global Flags</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto animate-in fade-in slide-in-from-bottom-6 duration-700 delay-200">
            From the deep blue of the Pacific to the vibrant colors of the African savanna, explore every nation's visual identity in one place.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-300">
            <Link href="/browse">
              <Button size="lg" className="h-14 px-10 text-lg font-bold shadow-lg shadow-primary/20">
                Browse Collection
              </Button>
            </Link>
            <Link href="/quiz">
              <Button size="lg" variant="secondary" className="h-14 px-10 text-lg font-bold group">
                Take the AI Quiz <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" />
              </Button>
            </Link>
          </div>
        </div>

        {/* Decorative elements */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full max-w-6xl -z-10 opacity-[0.03] pointer-events-none">
          <Globe2 className="w-full h-full text-primary" />
        </div>
      </section>

      {/* Featured Grid Section */}
      <section className="container mx-auto px-4 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="border-none shadow-md bg-white hover:shadow-xl transition-all">
            <CardContent className="p-8 space-y-4">
              <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                <Search className="h-6 w-6" />
              </div>
              <h3 className="text-xl font-headline font-bold">Fast Search</h3>
              <p className="text-muted-foreground">Quickly find any country flag and discover essential information like capital cities and regions.</p>
            </CardContent>
          </Card>
          
          <Card className="border-none shadow-md bg-white hover:shadow-xl transition-all">
            <CardContent className="p-8 space-y-4">
              <div className="h-12 w-12 rounded-xl bg-accent/10 flex items-center justify-center text-accent">
                <BrainCircuit className="h-6 w-6" />
              </div>
              <h3 className="text-xl font-headline font-bold">AI Quiz</h3>
              <p className="text-muted-foreground">Dynamic quizzes generated by GenAI to challenge your memory and help you learn faster.</p>
            </CardContent>
          </Card>

          <Card className="border-none shadow-md bg-white hover:shadow-xl transition-all">
            <CardContent className="p-8 space-y-4">
              <div className="h-12 w-12 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-500">
                <Globe2 className="h-6 w-6" />
              </div>
              <h3 className="text-xl font-headline font-bold">Continent Filters</h3>
              <p className="text-muted-foreground">Easily browse flags by continent to focus your study on specific regions of the world.</p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Random Flag Showcase */}
      <section className="container mx-auto px-4 py-20">
        <div className="bg-primary/5 rounded-[2rem] p-12 relative overflow-hidden">
          <div className="flex flex-col md:flex-row items-center gap-12 relative z-10">
            <div className="flex-1 space-y-6">
              <h2 className="text-3xl font-headline font-bold">Random Flag Spotlight</h2>
              <p className="text-lg text-muted-foreground max-w-md">
                Learning one flag at a time is a great way to build your global knowledge. Did you know this one?
              </p>
              <div className="flex gap-4">
                <Button onClick={pickRandomCountry} variant="outline" className="gap-2 h-12 px-6 border-primary text-primary hover:bg-primary/5">
                  <RefreshCw className="h-4 w-4" /> Spin Again
                </Button>
                {randomCountry && (
                  <Button onClick={() => setSelectedCountry(randomCountry)} variant="secondary" className="h-12 px-6">
                    View Details
                  </Button>
                )}
              </div>
            </div>
            
            <div className="flex-1 flex justify-center">
              {randomCountry && (
                <div 
                  className="group relative cursor-pointer"
                  onClick={() => setSelectedCountry(randomCountry)}
                >
                  <div className="absolute -inset-4 bg-primary/20 blur-2xl rounded-full opacity-0 group-hover:opacity-100 transition-opacity" />
                  <div className="relative aspect-[3/2] w-64 md:w-96 shadow-2xl rounded-lg overflow-hidden border-8 border-white">
                    <Image
                      src={randomCountry.flagUrl}
                      alt={randomCountry.name}
                      fill
                      className="object-cover"
                    />
                  </div>
                  <div className="mt-6 text-center">
                    <h3 className="text-2xl font-headline font-black text-primary">{randomCountry.name}</h3>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      <CountryDetailsDialog
        country={selectedCountry}
        isOpen={!!selectedCountry}
        onClose={() => setSelectedCountry(null)}
      />

      <footer className="container mx-auto px-4 pt-10 border-t mt-20 text-center">
        <p className="text-muted-foreground text-sm">
          &copy; {new Date().getFullYear()} GeoJourney. Built for global explorers.
        </p>
      </footer>
    </div>
  );
}
