
# Geovideography Deep-Grid Schema
# Hierarchy: Country -> LGA -> Town -> Street

type Country @table {
  id: UUID! @default(expr: "uuid_generate_v4()")
  name: String!
  flagUrl: String!
  history: String!
  population: Int!
  continent: String!
  lat: Float!
  lng: Float!
}

type LGA @table {
  id: UUID! @default(expr: "uuid_generate_v4()")
  name: String!
  country: Country!
}

type Town @table {
  id: UUID! @default(expr: "uuid_generate_v4()")
  name: String! @searchable
  lga: LGA!
}

type Street @table {
  id: UUID! @default(expr: "uuid_generate_v4()")
  name: String! @searchable
  town: Town!
  videoUrl: String
  treeCount: Int
  roadConditionScore: Float
  healthIndex: Float
  embedding: Vector @size(768)
}
